name: CI/CD
on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'renovate/**'
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - 'openapi.yaml'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:
jobs:
  backend-check:
    runs-on: ubuntu-latest
    name: Backend Checks
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # all history

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt

      - name: Restore Development Environment
        run: poetry install
        working-directory: backend

      - name: Check code is syntactically correct
        shell: bash
        run: poetry run poe compile
        working-directory: backend

      - name: Static Checks
        shell: bash
        run: poetry run poe static-checks
        working-directory: backend

      - name: Format Check
        shell: bash
        run: poetry run poe format-check
        working-directory: backend

      - name: Test with Coverage
        shell: bash
        run: |
          poetry run poe coverage
          poetry run poe coverage-report
          poetry run poe coverage-html
        working-directory: backend

      - uses: actions/upload-artifact@v7
        with:
          name: coverage-report-${{ github.sha }}
          path: backend/htmlcov
          if-no-files-found: ignore
          overwrite: true

  frontend-test:
    runs-on: ubuntu-latest
    name: Frontend Tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: frontend/package.json
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Test frontend
        run: npm tests
        working-directory: frontend

  backend-test:
    needs: backend-check
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          # - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    runs-on: ${{ matrix.os }}
    name: Backend Test on Python ${{ matrix.python-version }}, on ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt

      - name: Restore Development Environment
        run: poetry install
        working-directory: backend

      - name: Test
        shell: bash
        run: poetry run poe test
        working-directory: backend

  deploy:
    name: Deploy
    permissions:
      contents: write
      packages: write
    needs:
      - backend-test
      - frontend-test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
